// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamApi.Data;

#nullable disable

namespace TeamApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423205355_SeedInitialCreate")]
    partial class SeedInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamApi.Models.FavoriteFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContinentOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContinentOrigin = "North America",
                            FoodName = "Fried Chicken",
                            IsHot = true,
                            IsVegetarian = false
                        },
                        new
                        {
                            Id = 2,
                            ContinentOrigin = "Asia",
                            FoodName = "Yogurt",
                            IsHot = false,
                            IsVegetarian = true
                        },
                        new
                        {
                            Id = 3,
                            ContinentOrigin = "North America",
                            FoodName = "CheeseBurger",
                            IsHot = true,
                            IsVegetarian = false
                        },
                        new
                        {
                            Id = 4,
                            ContinentOrigin = "Europe",
                            FoodName = "Fettaccine Alfredo",
                            IsHot = true,
                            IsVegetarian = false
                        });
                });

            modelBuilder.Entity("TeamApi.Models.FavoriteVideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteVideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Turn-Based RPG",
                            HoursPlayed = 895,
                            Platform = "Desktop",
                            Title = "Baldurs Gate 3"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Strategy",
                            HoursPlayed = 700,
                            Platform = "Desktop",
                            Title = "Rollercoaster Tycoon 2"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Dungeon Crawler, Roguelite",
                            HoursPlayed = 2,
                            Platform = "Desktop",
                            Title = "Sol cesto"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "FPS",
                            HoursPlayed = 1153,
                            Platform = "Desktop",
                            Title = "MechWarrior Online"
                        });
                });

            modelBuilder.Entity("TeamApi.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("int");

                    b.Property<int>("YearsDoingIt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Playing video games with friends.",
                            Name = "Video Games",
                            WeeklyHours = 14,
                            YearsDoingIt = 16
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lifting weights",
                            Name = "Weightlifting",
                            WeeklyHours = 5,
                            YearsDoingIt = 6
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reading Manga",
                            Name = "Manga",
                            WeeklyHours = 24,
                            YearsDoingIt = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cooking meals for myself and others.",
                            Name = "Cooking",
                            WeeklyHours = 9,
                            YearsDoingIt = 8
                        });
                });

            modelBuilder.Entity("TeamApi.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2004, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology, Systems Adminstration and Game Design",
                            FullName = "Gabriel Boehm",
                            YearInProgram = "Third Year, Junior"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2001, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT Software Development",
                            FullName = "Van Diep",
                            YearInProgram = "Second Year, Sophmore"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2002, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT Software Development",
                            FullName = "Jane Doe",
                            YearInProgram = "First Year, Freshman"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2005, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Trade School",
                            FullName = "Adrian Taveras",
                            YearInProgram = "Second Year, Sophmore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
